vim.g.mapleader = " "
vim.g.maplocalleader = " "
vim.opt.compatible = false
vim.opt.number = true
vim.opt.mouse = "a"
vim.opt.showmode = false
vim.opt.clipboard = "unnamedplus"
vim.opt.breakindent = true
vim.opt.undofile = true
vim.opt.ignorecase = true
vim.opt.smartcase = true
vim.opt.signcolumn = "yes"
vim.opt.updatetime = 250
vim.opt.timeoutlen = 300
vim.opt.splitright = true
vim.opt.splitbelow = true
vim.opt.list = true
vim.opt.listchars = { tab = "» ", trail = "·", nbsp = "␣" }
vim.opt.inccommand = "split"
vim.opt.cursorline = true
vim.opt.scrolloff = 10
vim.opt.hidden = true
vim.opt.expandtab = true
vim.opt.laststatus = 3
-- vim.opt.confirm = true
vim.opt.termguicolors = true
vim.opt.tabstop = 4
vim.opt.softtabstop = -1
vim.opt.shiftwidth = 0
vim.opt.shiftround = true
vim.opt.smartindent = true
vim.opt.linebreak = true
vim.opt.wildmode = "longest:full,full"
vim.opt.swapfile = false
vim.opt.cmdheight = 0
vim.opt.relativenumber = true
vim.opt.foldlevel = 10
vim.opt.foldlevelstart = 10
vim.opt.foldminlines = 10
--vim.opt.foldcolumn = "1"
-- vim.opt.foldmethod = "expr"
-- vim.opt.foldexpr = "v:lua.vim.treesitter.foldexpr()"
